name: Generate PDF Book

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output
          echo "::set-env name=FILELIST::$(printf '"%s" ' src/*.md)"
      - uses: docker://pandoc/latex:2.9
        with:
          args: >-
            --table-of-contents
            --number-sections
            --pdf-engine=xelatex
            --indented-code-classes=zig
            --highlight-style=monochrome
            -V documentclass=report
            -V papersize=A4
            -V geometry:margin=1in
            --output=output/systems_programming_in_zig.pdf ${{ env.FILELIST }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
